name: Publish Package

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'apps/main-project/**'

jobs:
  publish:
    name: Publish to 120server
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 安装 Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

        # 3. 安装 pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          pnpm install --no-frozen-lockfile

      - name: Build
        working-directory: apps/main-project
        run: pnpm run build -- --mode prod.hw120

      - name: remove old version
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HW_MAIN_SERVER_HOST }}
          username: ${{ secrets.HW_MAIN_SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.HW_MAIN_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.HW_MAIN_DEPLOY_PATH }}
            rm -rf ./dist

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HW_MAIN_SERVER_HOST }}
          username: ${{ secrets.HW_MAIN_SERVER_USER }}
          key: ${{ secrets.HW_MAIN_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: 'dist/*'
          target: ${{ secrets.HW_MAIN_DEPLOY_PATH }}
          script: |
            cd ${{ secrets.HW_MAIN_DEPLOY_PATH }}
            ./restart_nginx.sh
